import crypto from 'crypto'

/**
 * @RegExp UUID_REGEX
 * @description Matches the RFC4122v4 UUID generated by createUuid
 */
export const UUID_REGEX = /^[a-zA-Z\d]{8}-[a-zA-Z\d]{4}-[a-zA-Z\d]{4}-[a-zA-Z\d]{4}-[a-zA-Z\d]{12}$/g

/**
 * @function createUuid
 * @description Generates a UUID that is compliant with RFC4122v4
 */
export const createUuid = (): string => {
    const placeholder = (([ 1e7 ] as any) + -1e3 + -4e3 + -8e3 + -1e11);
    const uuid = placeholder.replace(/[018]/g, (character: number) => {
        const randomNumber = (crypto.randomFillSync(new Uint8Array(1))[0] & 15) >> (character / 4);
        const randomString = (character ^ randomNumber).toString(16);
        return randomString;
    });

    return uuid;
}